version: "3"

services:

  infomarket_app:
    build: docker/php
    volumes:
      - ./:/app
    depends_on:
      - infomarket_db
      - mailcatcher
    env_file:
      - .env
    expose:
          - $NGINX_PUBLIC_PORT

  webpacker:
    image: node:9-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/true

  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=$SOCKET_DOMAIN
      - VIRTUAL_PORT=$NGINX_PUBLIC_PORT
      - HTTPS_METHOD=nohttps
    ports:
      - $NGINX_PUBLIC_PORT:$NGINX_PUBLIC_PORT
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - infomarket_app

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - $MAIL_PUBLIC_PORT:1080

  infomarket_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - $DB_PUBLIC_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - infomarket_db
    environment:
      - PMA_HOST=infomarket_db
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - $MYADMI_PUBLIC_PORT:80

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    ports:
      - $RABBITMQ_PUBLIC_PORT:5672
      - $RABBITMQ_UI_PUBLIC_PORT:15672

networks:
  default:
    external:
      name: projects_default
